name: formatting

on:
  push:
    paths:
      - 'streamable/**'
      - 'tests/**'
      - '.github/workflows/formatting.yml'

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: checks
      run: make venv format-check
