name: testing

on:
  push:
    paths:
      - 'streamable/**'
      - 'tests/**'
      - '.github/workflows/testing.yml'

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.14.0-beta.1'] # Default to latest Python for all OS
        include:
          # Specific Ubuntu Python versions
          - os: ubuntu-latest
            python-version: '3.8.18'
          - os: ubuntu-latest
            python-version: '3.9.18'
          - os: ubuntu-latest
            python-version: '3.10.13'
          - os: ubuntu-latest
            python-version: '3.11.7'
          - os: ubuntu-latest
            python-version: '3.12.1'
          - os: ubuntu-latest
            python-version: '3.13.1'
          - os: ubuntu-latest
            python-version: 'pypy-3.10'
          # Python 3.7.17 on an older Ubuntu runner
          - os: ubuntu-22.04
            python-version: '3.7.17'
          # First Python version for macOS and Windows
          - os: macos-latest
            python-version: '3.7.17'
          - os: windows-latest
            python-version: '3.7.17'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: unittest
        run: |
          python -m pip install -r tests/requirements.txt
          python -m unittest
