name: testing

on:
  push:
    paths:
      - 'streamable/**'
      - 'tests/**'
      - '.github/workflows/testing.yml'

jobs:
  testing:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ['3.7.17', '3.8.18', '3.9.18', '3.10.13', '3.11.7', '3.12.1', '3.13.1', '3.14.0-beta.1']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: unittest
        run: |
          python -m pip install -r tests/requirements.txt
          python -m unittest
